server:
  port: 81

# mysql
spring:
  application:
    name: cwlmall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.40.130:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev # 表示开发环境
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com:
      cwl:
        mall:
          product:
            dao: debug



