server:
  port: 88

spring:
  application:
    name: cwlmall-gateway
  cloud:
    gateway:
      routes:
        - id: admin_route
          uri: lb://cwlmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

