server:
  port: 84

# mysql
spring:
  application:
    name: cwlmall-coupon
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.40.130:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver



  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  mapperLocations: classpath:mapper/**/*.xml



